version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - cd ${CODEBUILD_SRC_DIR}/lambdas/
#      - pip install -r layers/simple-salesforce/requirements.txt
#      - pip install -r requirements.txt
#
#  pre_build:
#    commands:
#      - echo "Assume Temporary AWS Credentials"
#      - TEMP_ROLE=$(aws sts assume-role --role-arn $DEPLOY_ROLE_ARN --role-session-name get-secret-sitetracker)
#      - export TEMP_ROLE
#      - export AWS_ACCESS_KEY_ID=$(echo "${TEMP_ROLE}" | jq -r '.Credentials.AccessKeyId')
#      - export AWS_SECRET_ACCESS_KEY=$(echo "${TEMP_ROLE}" | jq -r '.Credentials.SecretAccessKey')
#      - export AWS_SESSION_TOKEN=$(echo "${TEMP_ROLE}" | jq -r '.Credentials.SessionToken')
#
#  build:
#    commands:
#      - cd ${CODEBUILD_SRC_DIR}/lambdas/
#      - echo "Running Pytest"
#      - python -m pytest . --junitxml=results.xml
#
#  post_build:
#    commands:
#      - export BuildID=`echo $CODEBUILD_BUILD_ID | cut -d:"" -f1`
#      - export BuildTag=`echo $CODEBUILD_BUILD_ID | cut -d:"" -f2`
#      - export Region=$AWS_REGION
#      - echo "Report '${CODEBUILD_BUILD_ID}' generated"
#      - echo "Report exported to '${BuildTag}-Pytest-reports' Report Group"
#
#reports:
#  Pytest-reports:
#    files:
#      - lambdas/results.xml
#    file-format: "JUNITXML"
