openapi: 3.0.0
x-definitions:
  x-amazon-apigateway-integration: &x-amazon-apigateway-integration
  security: &security
  x-amazon-apigateway-gateway-responses: &x-amazon-apigateway-gateway-responses
  x-amazon-apigateway-request-validators: &x-amazon-apigateway-request-validators
  securitySchemes: &securitySchemes
  methodOptions: &methodsOptions
servers:
  - url: "https://api.test.vantageapi.com/{basePath}"
    variables:
      basePath:
        default: "projectOutbound"
    x-amazon-apigateway-endpoint-configuration:
      disableExecuteApiEndpoint: true
info:
  description: This API provides operations to update and close a Project Outbound.
  version: 1.0.0
  title: ProjectOutbound
tags:
  - name: projectOutbound
    description: ProjectOutbound
x-amazon-apigateway-gateway-responses: *x-amazon-apigateway-gateway-responses
x-amazon-apigateway-request-validators: *x-amazon-apigateway-request-validators
x-amazon-apigateway-request-validator: "full"
paths:
  /:
    get:
      x-amazon-apigateway-request-validator: full
      security: *security
      x-amazon-apigateway-integration: *x-amazon-apigateway-integration
      tags:
        - projectOutbound
      summary: List or find Project Outbound objects
      description: This operation list of find Project Outbound objects
      operationId: listProjectOutbound
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ProjectOutbound"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "405":
          description: Method Not Allowed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "409":
          description: Conflict
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    options: *methodsOptions
  /{externalProjectId}:
    patch:
      x-amazon-apigateway-request-validator: full
      security: *security
      x-amazon-apigateway-integration: *x-amazon-apigateway-integration
      tags:
        - projectOutbound
      summary: Updates partially a Project Outbound
      description: This operation updates partially a Project Outbound entity
      operationId: patchProjectOutbound
      parameters:
        - name: externalProjectId
          in: path
          description: External Identifier of the Project Outbound
          required: true
          schema:
            type: string
      requestBody:
        description: The Project Outbound to be updated
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProjectOutboundUpdate"
      responses:
        "200":
          description: Updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProjectOutbound"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/Error"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/Error"
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/Error"
        "405":
          description: Method Not Allowed
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/Error"
        "409":
          description: Conflict
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/Error"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/Error"
    options: *methodsOptions
  /{externalProjectId}/close:
    post:
      x-amazon-apigateway-request-validator: full
      security: *security
      x-amazon-apigateway-integration: *x-amazon-apigateway-integration
      tags:
        - projectOutbound
      summary: Closes a Project Outbound
      description: This operation closes a Project Outbound entity
      operationId: closeProjectOutbound
      parameters:
        - name: externalProjectId
          in: path
          description: External Identifier of the Project Outbound
          required: true
          schema:
            type: string
      requestBody:
        description: The Project Outbound to be closed
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProjectOutboundClose"
      responses:
        "200":
          description: Closed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProjectOutbound"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/Error"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/Error"
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/Error"
        "405":
          description: Method Not Allowed
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/Error"
        "409":
          description: Conflict
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/Error"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/Error"
    options: *methodsOptions
components:
  schemas:
    ProjectOutbound:
      type: object
      description: The root entity for Project Outbound.
      additionalProperties: false
      properties:
        id:
          description: Unique identifier of the Project Outbound
          type: string
          minLength: 1
          maxLength: 18
          example: a3S0D000000WhCGUA0
        href:
          description: Unique reference of the Project Outbound
          type: string
        "@baseType":
          description: When sub-classing, this defines the super-class
          type: string
        "@schemaLocation":
          description: A URI to a JSON-Schema file that defines additional attributes and relationships
          type: string
          format: uri
        "@type":
          description: When sub-classing, this defines the sub-class entity name
          type: string
        name:
          description: Name of the Project Outbound
          type: string
          minLength: 1
          maxLength: 80
          example: P-551463
        externalProjectId:
          description: External Id of the Project Outbound
          type: string
          minLength: 1
          maxLength: 255
        customerProjectManagerName:
          description: Reference to user who is the manager of the Project Outbound
          type: string
          minLength: 1
          maxLength: 80
        closeComment:
          description: A section in which to post Project Outbound comments
          type: string
          minLength: 1
          maxLength: 255
        closeDate:
          description: Date sent by the MNO to be concatenated in the comment
          type: string
          format: date-time
          example: "2021-01-30T08:30:00Z"
        accountId:
          description: Unique identifier of the Account (MNO)
          type: string
          minLength: 1
          maxLength: 18
        accountName:
          description: Name of the Account (MNO)
          type: string
          minLength: 1
          maxLength: 255
    ProjectOutboundUpdate:
      type: object
      description: The root entity for Project Outbound. Skipped properties - externalProjectId,href
      additionalProperties: false
      required:
        - id
        - name
        - customerProjectManagerName
        - accountId
        - accountName
      properties:
        "@baseType":
          description: When sub-classing, this defines the super-class
          type: string
        "@schemaLocation":
          description: A URI to a JSON-Schema file that defines additional attributes and relationships
          type: string
          format: uri
        "@type":
          description: When sub-classing, this defines the sub-class entity name
          type: string
        id:
          description: Unique identifier of the Project Outbound
          type: string
          minLength: 1
          maxLength: 18
        name:
          description: Name of the Project Outbound
          type: string
          minLength: 1
          maxLength: 80
        customerProjectManagerName:
          description: Reference to user who is the manager of the Project Outbound
          type: string
          minLength: 1
          maxLength: 80
        accountId:
          description: Unique identifier of the Account (MNO)
          type: string
          minLength: 1
          maxLength: 18
        accountName:
          description: Name of the Account (MNO)
          type: string
          minLength: 1
          maxLength: 255
    ProjectOutboundClose:
      type: object
      description: The root entity for Project Outbound Close. Skipped properties - externalProjectId,href
      additionalProperties: false
      required:
        - id
        - name
        - closeDate
        - accountId
        - accountName
      properties:
        "@baseType":
          description: When sub-classing, this defines the super-class
          type: string
        "@schemaLocation":
          description: A URI to a JSON-Schema file that defines additional attributes and relationships
          type: string
          format: uri
        "@type":
          description: When sub-classing, this defines the sub-class entity name
          type: string
        id:
          description: Unique identifier of the Project Outbound
          type: string
          minLength: 1
          maxLength: 18
        name:
          description: Name of the Project Outbound
          type: string
          minLength: 1
          maxLength: 80
        closeComment:
          description: A section in which to post Project Outbound comments
          type: string
          minLength: 1
          maxLength: 255
        closeDate:
          description: Date sent by the MNO to be concatenated in the comment
          type: string
          format: date-time
          example: "2021-01-30T08:30:00Z"
        accountId:
          description: Unique identifier of the Account (MNO)
          type: string
          minLength: 1
          maxLength: 18
        accountName:
          description: Name of the Account (MNO)
          type: string
          minLength: 1
          maxLength: 255
    Error:
      type: object
      additionalProperties: false
      required:
        - code
        - reason
      properties:
        code:
          description: Application relevant detail, defined in the API or a common list.
          type: string
        reason:
          description: Explanation of the reason for the error which can be shown to a client user.
          type: string
        message:
          description: More details and corrective actions related to the error which can be shown to a client user.
          type: string
        status:
          description: HTTP Error code extension
          type: string
        referenceError:
          description: URI of documentation describing the error.
          type: string
          format: uri
        "@baseType":
          description: When sub-classing, this defines the super-class.
          type: string
        "@schemaLocation":
          description: A URI to a JSON-Schema file that defines additional attributes and relationships
          type: string
          format: uri
        "@type":
          description: When sub-classing, this defines the sub-class entity name.
          type: string
  securitySchemes: *securitySchemes
